### ISSUE TITLE
HA2024.7+: Clicking "Generate Rooms Config" doesn't do anything, and Selection is always empty

### ISSUE THREAD

**Issue by b-per** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#747] opened 2024-07-04 21:04 UTC
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am trying to set up my Dreame D10 Plus, but I have having issues getting the list of rooms from my camera.

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/8754100/aecb2ac5-0f34-4c0d-9dfb-b4974f65c7fd)

My camere is showing the map as expected but when I click "Generate Rooms Config" nothing happens. Similarly, when I add points to the map, the `Selection` value stays empty at `[]`.

I have also tried to save the card, close it and clicking again on the button but nothing happens.

If I follow [the instructions for < 2.1.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317) with the template though, it generates some configuration I can use.

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

dreame.vacuum.r2205

### Which integration do you use to control your vacuum (link)?

https://github.com/Tasshack/dreame-vacuum

### What browser (browsers/apps) does have this problem?

Chrome/Safari

### What version of Home Assistant do you use?

2024.7.0

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.booty_map
calibration_source:
  camera: true
entity: vacuum.booty
vacuum_platform: Tasshack/dreame-vacuum
```

### Javascript errors shown in the browser's console (if applicable)

```shell
None
```

**Comment by b-per** [comment] 2024-07-04 21:10
Here is my camera state as well

```
access_token: abcd
charger_position:
  x: 531
  "y": -52
  a: 180
rooms:
  "1":
    x0: 650
    y0: -10450
    x1: 1750
    y1: -1650
    room_id: 1
    name: Corridor
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 8
    index: 0
    icon: mdi:foot-print
    color_index: 0
    x: 1250
    "y": -5800
    letter: A
  "2":
    x0: 850
    y0: 1450
    x1: 4350
    y1: 3050
    room_id: 2
    name: Entrance
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 0
    index: 0
    icon: mdi:home-outline
    color_index: 1
    x: 2600
    "y": 2400
    letter: B
  "3":
    x0: 1600
    y0: -3900
    x1: 3650
    y1: 1600
    room_id: 3
    name: Kitchen
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 4
    index: 0
    icon: mdi:chef-hat
    color_index: 2
    x: 2650
    "y": -1150
    letter: C
  "4":
    x0: -3050
    y0: -5100
    x1: 700
    y1: -2700
    room_id: 4
    name: OfficeBen
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 0
    index: 1
    icon: mdi:home-outline
    color_index: 1
    x: -1500
    "y": -3850
    letter: D
  "6":
    x0: 1750
    y0: -6150
    x1: 3650
    y1: -4600
    room_id: 6
    name: Bathroom2
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 0
    index: 3
    icon: mdi:home-outline
    color_index: 2
    x: 2450
    "y": -5350
    letter: F
  "7":
    x0: -3050
    y0: -7600
    x1: 800
    y1: -5300
    room_id: 7
    name: OfficePat
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 0
    index: 2
    icon: mdi:home-outline
    color_index: 3
    x: -1500
    "y": -6400
    letter: G
  "8":
    x0: 1700
    y0: -10550
    x1: 3650
    y1: -7750
    room_id: 8
    name: Bathroom
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 6
    index: 0
    icon: mdi:toilet
    color_index: 1
    x: 2400
    "y": -9100
    letter: H
  "9":
    x0: -3800
    y0: -2550
    x1: 850
    y1: 3050
    room_id: 9
    name: Living Room
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 1
    index: 0
    icon: mdi:sofa-outline
    color_index: 3
    x: -1500
    "y": 500
    letter: I
  "12":
    x0: -3850
    y0: -10550
    x1: 700
    y1: -7800
    room_id: 12
    name: Primary Bedroom
    order: 0
    cleaning_times: 1
    suction_level: 1
    water_volume: 2
    type: 2
    index: 0
    icon: mdi:bed-king-outline
    color_index: 2
    x: -3050
    "y": -9300
    letter: L
vacuum_position:
  x: 531
  "y": -52
  a: 0
map_id: 3
rotation: 0
updated_at: "2024-07-04T22:43:10.236833"
used_times: 1
active_segments:
  - 4
  - 12
no_go_areas:
  - x0: -4103
    y0: -10758
    x1: -3540
    y1: -10758
    x2: -3540
    y2: -10195
    x3: -4103
    y3: -10195
  - x0: -2262
    y0: -5164
    x1: -1154
    y1: -5164
    x2: -1154
    y2: -4582
    x3: -2262
    y3: -4582
  - x0: -3892
    y0: -294
    x1: -3329
    y1: -294
    x2: -3329
    y2: 261
    x3: -3892
    y3: 261
is_empty: false
frame_id: 448
calibration_points:
  - vacuum:
      x: 0
      "y": 0
    map:
      x: 384
      "y": 304
  - vacuum:
      x: 1000
      "y": 0
    map:
      x: 464
      "y": 304
  - vacuum:
      x: 0
      "y": 1000
    map:
      x: 384
      "y": 224
entity_picture: >-
  /api/camera_proxy/camera.booty_map?token=abcd
icon: mdi:map
friendly_name: Booty Current Map
supported_features: 0
```

**Comment by PiotrMachowski** [comment] 2024-07-05 09:31
Have you tried it on any previous version of the HA? Is the map card inside any other card?

**Comment by yeyeoke** [comment] 2024-07-05 12:46
I'm actually having the exact same problem with a Roborock S5 running Hypfer/Valetudo. On Homeassistant 2024.7.0 Here's my card configuration: 

`type: custom:xiaomi-vacuum-map-card
entity: vacuum.valetudo_s5
vacuum_platform: Hypfer/Valetudo
map_source:
  camera: camera.valetudo_s5_camera
calibration_source:
  camera: true
map_locked: true`

My card is not inside any other card, and I have not tried it on an earlier version since I just found out about this awesome card.

**Comment by PiotrMachowski** [comment] 2024-07-05 13:09
It is not a bug in HA, just it seems that something has been changed in it and this change broke this functionality in the card. I will check it out and adjust the code to the latest HA

**Comment by gatogatogato** [comment] 2024-07-09 11:35
Same issue with a Dreame L20 Ultra and a D10s Pro. Any ETA when this will be fixed? 

Btw thanks for this card, it's really amazing.

**Comment by PiotrMachowski** [comment] 2024-07-09 11:48
For Dreame integration you can use [this config template](https://github.com/Tasshack/dreame-vacuum/blob/179f6e14e86de4a4d5c5df4a7648026e013595d1/README.md#how-to-use) to generate rooms config. Then adjust vacuum platform and it should be fine.

At this moment there is not ETA, I will analyze this issue this weekend.

**Comment by gatogatogato** [comment] 2024-07-09 13:23
That worked like a charm - thanks for the workaround.

**Comment by aaronjoeldev** [comment] 2024-07-10 13:19
Is there also a fix for the roborock s7 already?
Because I am facing the same problem with mine.
Clicking on "generate rooms config" and nothing happens..
Around 6 month ago it used to work.

**Comment by frank2604** [comment] 2024-07-10 16:00
> For Dreame integration you can use [this config template](https://github.com/Tasshack/dreame-vacuum/blob/179f6e14e86de4a4d5c5df4a7648026e013595d1/README.md#how-to-use) to generate rooms config. Then adjust vacuum platform and it should be fine.
> 
> At this moment there is no ETA, I will analyze this issue this weekend.

Thanks. After figuring out how to - it worked perfect.

After completion the vacuum and camera entity in the head of the template, running it in the template dev tool inside HA it creates the complete card config which has to be copied into the code editor of the card.

Thanks for hinting us to the workaround.

**Comment by PiotrMachowski** [comment] 2024-07-11 14:16
Version from [this build](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/actions/runs/9893050395) potentially fixes this issue, but it requires manual installation.

**Comment by PiotrMachowski** [comment] 2024-07-12 01:16
Fixed in `v2.2.3`

**Closed by PiotrMachowski** 2024-07-12 01:16 UTC
Labels: bug

**Comment by muehlt** [comment] 2024-07-16 11:07
Just had a similar issue with "Generate Rooms Config" doing nothing. In my case it was related to the new experimental Sections Dashboard in home assistant, maybe that helps.

**Comment by PiotrMachowski** [comment] 2024-07-16 21:14
@muehlt yup, I need to adjust it as well

**Comment by PiotrMachowski** [comment] 2024-07-16 22:45
@muehlt fixed in `v2.2.4`

**Comment by DoomBudgie** [comment] 2025-03-29 19:02
Sorry to gravedig, but I'm just installing this now for a Roborock Q5 Max+ and the **Generate Rooms Config** button is greyed out. I also have an _Invalid calibration, please check your configuration_ alert. With this, selective room cleaning isn't available. Am I missing something?

**Comment by PiotrMachowski** [comment] 2025-03-29 19:04
@DoomBudgie please read the instructions here:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/templates/roborock.md

**Comment by DoomBudgie** [comment] 2025-03-29 19:34
Awesome, thank you! I see it currently needs the beta version 2025.4. Doing this with HACS seems to require the HACS: Get add on, which I can't seem to find. I guess I'll wait until the stable version of 2025.4 comes out.
