### ISSUE TITLE
Horizontal layout of the map and control

### ISSUE THREAD

**Issue by Sysoev86** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#394] opened 2022-05-08 11:44 UTC
### Description

Now the map and control are under each other
<img width="433" alt="Снимок экрана 2022-05-08 в 18 41 22" src="https://user-images.githubusercontent.com/57587845/167294514-2ca4dc8d-7e38-4d44-bff8-01484fb75b72.png">

Thank you

### Solution

I would like to be able to position the map and control vertically
To be able to use on 16:9 monitors in full screen
<img width="1431" alt="Снимок экрана 2022-05-08 в 18 43 50" src="https://user-images.githubusercontent.com/57587845/167294595-8ced2bf8-fa3a-4219-b1f8-2cfc715dcdc2.png">

**Comment by PiotrMachowski** [comment] 2022-05-08 12:13
Duplicate of #183

**Closed by PiotrMachowski** 2022-05-08 12:13 UTC
Labels: enhancement
