### ISSUE TITLE
Map interaction in Firefox or iOS App does not work properly

### ISSUE THREAD

**Issue by LeDomme** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#169] opened 2021-11-17 11:11 UTC
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi,

since the latest update the Pin & Go and the Zone cleanup function will not work in Firefox or on iOS via the Nabu Casa App.

On both Systems a click triggers a mark of the Card itself (blue border in app or hattched in firefox) and in (at least firefox) the debbuger console a TouchEvent is triggered.
With Chrome the Card works as expected.

JS Error from Debbuger Console attached

### What version of a card has described problem?

2.0.1

### What was the last working version card?

1.2.3

### What vacuum model do you have problems with?

Roborock S6 MaxV

### What version of Home Assistant do you use?

core-2021.11.4

### What type of installation are you running?

Home Assistant OS

### Javascript errors shown in the browser's console (if applicable)

```shell
Uncaught ReferenceError: TouchEvent is not defined
    Pt xiaomi-vacuum-map-card.js:126
    _mouseUp xiaomi-vacuum-map-card.js:994
    u xiaomi-vacuum-map-card.js:858
    handleEvent xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    t xiaomi-vacuum-map-card.js:37
    update xiaomi-vacuum-map-card.js:37
    performUpdate xiaomi-vacuum-map-card.js:25
    q xiaomi-vacuum-map-card.js:25
    requestUpdate xiaomi-vacuum-map-card.js:25
    u xiaomi-vacuum-map-card.js:25
    v xiaomi-vacuum-map-card.js:25
    ne xiaomi-vacuum-map-card.js:37
    fa xiaomi-vacuum-map-card.js:838
    s ha-logbook.ts:28
    d ha-logbook.ts:28
    d ha-logbook.ts:28
    c ha-logbook.ts:28
    b ha-logbook.ts:28
    value hui-stack-card.ts:16
    _cards hui-light-card.ts:35
    value hui-light-card.ts:35
    setConfig d8008d9a.js:1
    s ha-logbook.ts:28
    d ha-logbook.ts:28
    d ha-logbook.ts:28
    c ha-logbook.ts:28
    b ha-logbook.ts:28
    value hui-stack-card.ts:16
    _cards hui-light-card.ts:35
    value hui-light-card.ts:35
    setConfig d8008d9a.js:1
    d ha-logbook.ts:28
    promise callback*7778/d/< ha-logbook.ts:28
    d ha-logbook.ts:28
    c ha-logbook.ts:28
    b ha-logbook.ts:28
```

**Comment by PiotrMachowski** [comment] 2021-11-17 11:30
Duplicate of #130

**Closed by PiotrMachowski** 2021-11-17 11:30 UTC
Labels: bug

**Comment by HepoH3** [comment] 2021-11-17 11:31
It seems to be duplicate of #130.
