### ISSUE TITLE
Better design for panel mode

### ISSUE THREAD

**Issue by kimme1024** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#247] opened 2021-12-07 14:56 UTC
### Description

To be able to display everything fullscreen on my wall mounted tablet I'm using panel mode for my dashboards.
However this card isn't really compatible with it.

The card is extremely zoomed in to fill in the sides, therefore the vacuums data on the bottom can't be shown. Also I'm not able to scroll down to that data and the crop function isn't working. It only seems to work in tile mode.

### Solution

Adapt the card to panel mode, maybe putting the vacuum data on top instead of bottom (or add function to choose).
Fix the crop function to work with panel mode as well as the ability to scroll.

**Comment by PiotrMachowski** [comment] 2021-12-07 15:44
Duplicate of #183

**Closed by PiotrMachowski** 2021-12-07 15:44 UTC
Labels: enhancement
