### ISSUE TITLE
Add default hold action to reset consumables

### ISSUE THREAD

**Issue by incaseoftrouble** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#462] opened 2022-08-25 14:13 UTC
### Description

First: Thanks a lot for this really awesome card!

While playing with it, I found that it would be nice to be able to reset the consumables (filter, brush, sensor, etc.) through the appropriate buttons. I "hacked" this by manually overriding the `tiles:` (see code below), however this is a bit cumbersome.

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_s5e
vacuum_platform: default
two_finger_pan: true
map_locked: false
tiles:
  - label: Status
    icon: mdi:robot-vacuum
    entity: vacuum.roborock_vacuum_s5e
    attribute: status
  - label: Battery
    icon: mdi:battery
    entity: vacuum.roborock_vacuum_s5e
    attribute: battery_level
    unit: '%'
  - label: Fan speed
    icon: mdi:fan
    entity: vacuum.roborock_vacuum_s5e
    attribute: fan_speed
  - label: Sensors left
    icon: mdi:eye-outline
    entity: sensor.roborock_vacuum_s5e_sensor_dirty_left
    unit: h
    multiplier: 0.000277778
    precision: 0
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
      target:
        device_id: ---
  - label: Filter left
    icon: mdi:air-filter
    entity: sensor.roborock_vacuum_s5e_filter_left
    unit: h
    multiplier: 0.000277778
    precision: 0
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params: filter_work_time
      target:
        device_id: ---
  - label: Main brush left
    icon: mdi:brush
    entity: sensor.roborock_vacuum_s5e_main_brush_left
    unit: h
    multiplier: 0.000277778
    precision: 0
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params: main_brush_work_time
      target:
        device_id: ---
  - label: Sensors left
    icon: mdi:brush
    entity: sensor.roborock_vacuum_s5e_side_brush_left
    unit: h
    multiplier: 0.000277778
    precision: 0
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params: side_brush_work_time
      target:
        device_id: ---
```
(removed the device id)

### Solution

I'd guess that this is a reasonable behavior to have by default, so maybe one could add an attribute to the template or a separate template (`default_with_reset` or so?). However, I am unsure what's the best way to implement this.

### Context

Side note: While adding the `hold_action` I found that this card expects the service call data to be given as `service_data:` in the YAML, while normal home assistant actions are parametrized by `data:`. Maybe it makes sense to keep this in sync?

**Comment by PiotrMachowski** [comment] 2022-08-25 15:14
> I "hacked" this by manually overriding the `tiles:`

That's a feature, not a hack 😃 

In the next release there will be an easier way to manually change autogenerated configuration, so I think I will add resetting consumables by default and users will be able to easily remove it from their configs.



> Side note: While adding the `hold_action` I found that this card expects the service call data to be given as `service_data:` in the YAML, while normal home assistant actions are parametrized by `data:`. Maybe it makes sense to keep this in sync?

This was caused by basing on [boilerplate card](https://github.com/custom-cards/boilerplate-card), changing it to be in sync with HA makes sense, I will try to do it with minimal breaking changes

**Comment by PiotrMachowski** [comment] 2022-08-25 20:29
> Side note: While adding the `hold_action` I found that this card expects the service call data to be given as `service_data:` in the YAML, while normal home assistant actions are parametrized by `data:`. Maybe it makes sense to keep this in sync?

Actually, it is caused by [custom-card-helpers](https://github.com/custom-cards/custom-card-helpers/blob/master/src/handle-action.ts#L74), as it expects `service_data` field, not `data`

**Comment by incaseoftrouble** [comment] 2022-08-25 22:54
Totally fine with me! Maybe adding a remark / example in the README might be good :smile: The section "Tile list entry options" links to HA's action definition, which suggests the `data:` format.

**Comment by PiotrMachowski** [comment] 2022-08-25 22:59
I have added it on `dev` branch ;)

**Comment by incaseoftrouble** [comment] 2022-08-26 07:46
Cool!

> In the next release there will be an easier way to manually change autogenerated configuration, so I think I will add resetting consumables by default and users will be able to easily remove it from their configs.

with this I think my issue is addressed then! It might be nice to selectively replace tiles (so instead of a list, have a map with some names and if the name matches a default tile and `append_tiles: true`, that one default tile is replaced). but this is just an idea.

**Comment by PiotrMachowski** [comment] 2022-08-26 08:08
Let's not close this issue until functionality is released.

> It might be nice to selectively replace tiles (so instead of a list, have a map with some names and if the name matches a default tile and `append_tiles: true`

I'll think about something like this.

**Comment by PiotrMachowski** [comment] 2022-08-26 16:58
I have added `tile_id` https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/tree/dev#tile-list-entry-options

**Comment by PiotrMachowski** [comment] 2022-09-13 02:12
Feature added in v2.1.0

**Closed by PiotrMachowski** 2022-09-13 02:12 UTC
Labels: enhancement, done on dev
