### ISSUE TITLE
Uncaught ReferenceError: TouchEvent is not defined (Firefox)

### ISSUE THREAD

**Issue by Perrep** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#158] opened 2021-11-16 14:54 UTC
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

So while this i working perfectly in the App and in chrome, its not working in firefox. 

This might be the solution: https://stackoverflow.com/questions/27313488/touchevent-not-working-in-firefox-and-other-website-browser

### What version of a card has described problem?

v2.0.1

### What vacuum model do you have problems with?

s5max

### What version of Home Assistant do you use?

2021.10.4

### What type of installation are you running?

Home Assistant OS

### Javascript errors shown in the browser's console (if applicable)

```shell
Uncaught ReferenceError: TouchEvent is not defined
    _drag xiaomi-vacuum-map-card.js:181
    render xiaomi-vacuum-map-card.js:150
    handleEvent xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    g xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    t xiaomi-vacuum-map-card.js:37
    update xiaomi-vacuum-map-card.js:37
    performUpdate xiaomi-vacuum-map-card.js:25
    q xiaomi-vacuum-map-card.js:25
    requestUpdate xiaomi-vacuum-map-card.js:25
    _addRectangle xiaomi-vacuum-map-card.js:994
    _createMapControls xiaomi-vacuum-map-card.js:964
    handleEvent xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    g xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    v xiaomi-vacuum-map-card.js:31
    _ xiaomi-vacuum-map-card.js:31
    I xiaomi-vacuum-map-card.js:31
    t xiaomi-vacuum-map-card.js:37
    update xiaomi-vacuum-map-card.js:37
    performUpdate xiaomi-vacuum-map-card.js:25
    q xiaomi-vacuum-map-card.js:25
    requestUpdate xiaomi-vacuum-map-card.js:25
    set xiaomi-vacuum-map-card.js:25
    _setCurrentMode xiaomi-vacuum-map-card.js:994
    render xiaomi-vacuum-map-card.js:943
    render xiaomi-vacuum-map-card.js:739
    handleEvent xiaomi-vacuum-map-card.js:31
    fire typography.js:181
    _applySelection be3db3b8.js:2
    _applySelection be3db3b8.js:2
xiaomi-vacuum-map-card.js:181:958
```

**Comment by PiotrMachowski** [comment] 2021-11-16 15:42
Thank you for detailed info, but this issue has already been raised.

Duplicate of #130 ,

**Closed by PiotrMachowski** 2021-11-16 15:42 UTC
Labels: bug
