### ISSUE TITLE
Rooms not displaying on mobile

### ISSUE THREAD

**Issue by datbilling** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#188] opened 2021-11-18 22:04 UTC
Rooms are displaying fine on PC but not on the Home Assistant app or mobile site on Safari iOS. The icons appear on the top left corner on top of each other, rather than on each room. There's also no outline around the rooms or labels showing.

![image](https://user-images.githubusercontent.com/58982799/142504502-e741d40e-d272-471c-85a7-4b8f6c6e336b.jpeg)

**Comment by PiotrMachowski** [comment] 2021-11-18 22:09
Duplicate of #130

**Closed by PiotrMachowski** 2021-11-18 22:09 UTC
