### ISSUE TITLE
Support for ijai.vacuum.v3

### ISSUE THREAD

**Issue by markosopcic** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#585] opened 2023-05-09 23:04 UTC
### Description

The ijai.vacuum.v3, or in other words, the Vacuum Mop 2 Pro is a pretty popular device in my country, it would be great if you could provide support for it as well.

### Solution

Add support for ijai.vacuum.v3.

**Comment by PiotrMachowski** [comment] 2023-05-09 23:42
Duplicate of #200

**Closed by PiotrMachowski** 2023-05-09 23:42 UTC
Labels: enhancement
