### ISSUE TITLE
If you turn the camera

### ISSUE THREAD

**Issue by NikiHard** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#201] opened 2021-11-22 06:27 UTC
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

If you turn the camera, then the zone selection does not work correctly

### What version of a card has described problem?

2.0.3

### What vacuum model do you have problems with?

roborock_s6_maxv

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2021.11.5

### What type of installation are you running?

Home Assistant Container

### Additional information

https://user-images.githubusercontent.com/14994565/142810903-ac434f2e-287d-4385-9b08-0af1786d8dda.mp4

**Comment by PiotrMachowski** [comment] 2021-11-22 08:58
Was everything working before v2.0.3?

**Comment by NikiHard** [comment] 2021-11-22 13:02
I haven't used it before))

**Comment by PiotrMachowski** [comment] 2021-11-22 13:21
Duplicate of #173 

Please provide config, calibration points from camera and check for errors in browser's console.

**Closed by PiotrMachowski** 2021-11-22 13:21 UTC
Labels: bug
