### ISSUE TITLE
Cannot expand menu to pick rooms mode - Home Assistant app

### ISSUE THREAD

**Issue by znanywawa** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#582] opened 2023-05-07 17:50 UTC
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

At newest Home Assistant Supervised and Home Assistant Android App (beta-9972-8b32f9bf-full) You cannot expand menu to pick rooms, only creation of ZONES is allowed. Issue is applicable to Mobile App as well as web browser (tested at Android Chrome web browser) while using mobile version of instance, but when I switch Android Chrome app to Desktop mode - it works with no issues through web browser.

### What version of a card has described problem?

v2.2.0-beta.1

### What vacuum model do you have problems with?

roborock.vacuum.a15

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

Android HA App, Android Chrome (in mobile mode)

### What version of Home Assistant do you use?

2023.5.2

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: vertical-stack
cards:
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.roborock_s7
    map_source:
      camera: camera.roborock_s7_map
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
      - template: vacuum_clean_segment
        predefined_selections:
          - icon:
              name: mdi:television
              x: 27400
              'y': 26350
            id: 17
          - icon:
              name: mdi:human-child
              x: 30600
              'y': 25975
            id: 18
          - icon:
              name: mdi:shower-head
              x: 25125
              'y': 30300
            id: 19
          - icon:
              name: mdi:bed
              x: 26100
              'y': 34500
            id: 20
          - icon:
              name: mdi:broom
              x: 27400
              'y': 31175
            id: 16
          - icon:
              name: mdi:bathtub
              x: 25475
              'y': 32325
            id: 21
    vacuum_platform: humbertogontijo/homeassistant-roborock
```

**Comment by PiotrMachowski** [comment] 2023-05-07 17:54
Duplicate of #481 

You can install the latest beta version to fix this issue

**Comment by znanywawa** [comment] 2023-05-07 17:57
@PiotrMachowski I dont see any newer beta version via HACS than v.2.2.0-beta.1
![image](https://user-images.githubusercontent.com/62244838/236694424-08ccdb6c-0dff-46e2-8e45-ad756cb79953.png)

**Comment by PiotrMachowski** [comment] 2023-05-07 18:00
Oh, I have missed that you already have it installed

Which Android version does your device have?

**Comment by znanywawa** [comment] 2023-05-07 18:03
No problem, it may happen :)

Its: Samsung Galaxy S20 FE 5G
Android 13.0
One UI version: 5.1

The issue came after HA recent updates (to 2023.05.x), previously it was working fine with this beta version of card.

**Comment by PiotrMachowski** [comment] 2023-05-07 18:10
Can you try to check if it works in incognito mode?

**Comment by znanywawa** [comment] 2023-05-07 18:12
Nope, it doesnt work even in incognito mode while page is loaded in "mobile mode". When I will switch it to "desktop mode" it works properly.

**Comment by PiotrMachowski** [comment] 2023-05-07 18:41
It works perfectly fine on my phone, maybe it depends on the size of viewport, can you check your values?

https://whatismyviewport.com/

**Comment by znanywawa** [comment] 2023-05-07 18:44
Values from my Chrome on Android (mobile mode):
412px x 825px
DPR: 2.63
Screen size: 412px x 915px

Values from my Chrome on Android (desktop mode):
980px x 1961px
DPR: 2.63
Scren size: 412px x 915px

**Comment by PiotrMachowski** [comment] 2023-05-08 00:14
Can you check if the same problem exists if the card is not enclosed in vertical stack?

**Comment by znanywawa** [comment] 2023-05-08 08:02
I have tested, and seems that if card isnt in vertical stack - works correctly. But previously, it was working even when in vertical stack.

**Comment by znanywawa** [comment] 2023-05-11 10:57
Any ideas how to fix that?
To be honest, I'd rather not changing current cards configuration and converting vertical stack current configuration.

**Comment by PiotrMachowski** [comment] 2023-06-03 00:33
Done in [v2.2.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0)

**Closed by PiotrMachowski** 2023-06-03 00:33 UTC
Labels: bug, done on dev
